### ISSUE TITLE
Next turn starts on showing cards with Szpieg.

### ISSUE THREAD

**Issue by mkondratek** [programistagd/TrachOnline#40]
Make player able to see cards beyond next turn time.

**Comment by radeusgd** [comment]
Turn time should be long enough to make it irrelevant.

Extend base turn time to 35s (or more?) and improve skipping (dead players don't have to). Also need to remember to make an empty turn turn into an empty discard (lose 1 life).

**Comment by radeusgd** [comment]
For now closing as wontfix, as the issue should be mitigated by lengthening turn time.
If there is a better solution, please reopen the issue
