### ISSUE TITLE
Unable to defend with same(?) previously deactivated card.

### ISSUE THREAD

**Issue by mkondratek** [programistagd/TrachOnline#48]
![trachbug](https://cloud.githubusercontent.com/assets/19799111/16868003/7c22718e-4a75-11e6-8e19-42fe8958ed28.png)

I defended with Nietykalny against Nadwrażliwy and couldn't  do it again after deactivation of first Nietykalny.

**Comment by radeusgd** [comment]
After a defending card has been played (Obrona / Nietykalny) and deactivated, it's impossible to try defending again. Investigating.

**Comment by radeusgd** [comment]
Fixed in 01fa4afe04da0847194960d23ce366b3bcd59a79
